### ISSUE TITLE
How to use this tool for human data?

### ISSUE THREAD

**Issue by YiweiNiu** [veltenlab/rnamagnet#1]
Hi,

Thanks for developing this nice tool!

I found that the ligand-receptor data in this package are for mice. I wonder if we could use this package along with interaction data from [cellphonedb](https://www.cellphonedb.org/downloads).

If the answer is yes, are there anything I should notice?

Any help would be appreciated.

**Comment by velten-lab** [comment]
Sorry for the delayed reply. Actually the evidence underlying these interactions is not really species specific, neither in our case, nor for cellphonedb as far as I understand. 
You can just translate the gene ids in the ligand-receptor table to human using biomart. Or you can download the cellphonedb interaction data and transform it to the format we were using. I hope that helps!

**Comment by YiweiNiu** [comment]
Thank you for your reply. It's not late at all. I would try it in our data.
